name: If Demo
on:
  push:
    branches:
      - main
      - develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref == 'ref/heads/main'
        run: echo "Running this step with condition"
      - name: Run this step
        run: echo "Running this without condition"
