name: Deploy App
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd
          - qa
      artifact_tag:
        description: "Choose tag to deploy"
        required: true
        
jobs:
 input-demo:
   runs-on: ubuntu-latest
   steps:
     - name: Deploy the app
       run: echo "Deployin the app to  ${{inputs.environment}} and tag is ${{inputs.artifact_tag}}"
     - name: Print all variables
       run: echo "${{toJson(github)}}"

     
     
